language: c

compiler:
  - gcc
arch:
  - ppc64le
  - amd64
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - bison
    - gcc-6
    - help2man
    - lzip
    - texinfo
    - texlive

before_script:
    - ./.travis/install-gettext.sh
    - ./.travis/install-automake.sh
    - export PATH=$HOME/bin:$PATH

script: ./autogen.sh && ./configure && make && make check && make distcheck
